Yd/adds streaming app
gear-foundation/dapps pull request #145
Opened 2023-11-30 19:32 UTC by YauheniDraichykau

2023-11-30 22:42 UTC, nikitayutanov requested changes

2023-11-30 22:42 UTC, nikitayutanov commented on frontend/apps/w3bstreaming/.env.example
> +REACT_APP_STREAMING_IPFS_NODE=
```suggestion
REACT_APP_CONTRACT_ADDRESS=0x3eb6f1f66560ee83603c8349c7959912266e7acded8b537cdbe4412937cad62a
REACT_APP_NODE_ADDRESS=wss://testnet.vara-network.io
REACT_APP_IPFS_GATEWAY_ADDRESS=
REACT_APP_IPFS_ADDRESS=
```
please stick to default naming in order for logPublicEnvs and errorTracking utils to work properly without any additional arguments.

2023-11-30 22:42 UTC, nikitayutanov commented on frontend/apps/w3bstreaming/.prettierrc
we have root prettierrc

2023-11-30 22:42 UTC, nikitayutanov commented on frontend/apps/w3bstreaming/.gitignore
we have root gitignore

2023-11-30 22:42 UTC, nikitayutanov commented on frontend/apps/w3bstreaming/package.json
> +    "@types/react-gtm-module": "2.0.1",
please use error tracking and analytics utils from shared packages, remove direct dependencies tied to it

2023-11-30 22:42 UTC, nikitayutanov commented on frontend/apps/w3bstreaming/package.json
> +    "eslint-config-airbnb": "19.0.4",
also provide strict versions for packages

2023-12-10 20:36 UTC, YauheniDraichykau commented
> Everything is good, but I don't see `initErrorTracking()`, `logPublicEnvs()` and `initAnalytics()` calls from `index.tsx`?

Fixed

2023-12-11 14:22 UTC, ereburg approved these changes

2023-12-11 15:05 UTC, nikitayutanov approved these changes

2023-12-11 15:52 UTC, merged