Tamagotchi-battle: Adds voucher
gear-foundation/dapps pull request #153
Opened 2023-12-06 12:08 UTC by YauheniDraichykau

2023-12-06 12:10 UTC, YauheniDraichykau commented on frontend/apps/tamagotchi-battle/src/app/hooks/use-fetch-voucher.ts
> +  console.log(isVoucherExists);
will remove it after testing

2023-12-07 08:12 UTC, faizov approved these changes

2023-12-07 21:11 UTC, nikitayutanov requested changes

2023-12-07 21:11 UTC, nikitayutanov commented on frontend/packages/gasless-transactions/src/hooks/use-fetch-voucher.ts
> +export function useFetchVoucher({ accountAddress, programId, backendAddress, voucherLimit }: UseFetchVoucherProps) {
Those arguments have the same origin across each app, I don't think that we should specify them explicitly. Better to do it in a convenient way in a package itself. As an example, you can look at `error-tracking` implementation.

- `accountAddress` is obtained from `useAccount` hook
- `programId` is usually env variable with default name `REACT_APP/VITE_CONTRACT_ADDRESS`
- `backendAddress` should be env variable with a default name too. My suggestion would be `GASLESS_BACKEND_ADDRESS`
- if `voucherLimit` preferrably would be controlled via env variable, same instructions as for above. I would suggest `GASLESS_BACKEND_VOUCHER_LIMIT`

2023-12-07 21:18 UTC, nikitayutanov requested changes

2023-12-07 21:18 UTC, nikitayutanov commented on frontend/apps/tamagotchi-battle/src/app/consts.ts
> +export const GAS_LIMIT = 250000000000;
Why specified gas limit is higher than what we've calculated before?

2023-12-11 14:34 UTC, nikitayutanov approved these changes

2023-12-11 14:35 UTC, merged