Refactoring multi-token
gear-foundation/dapps pull request #201
Opened 2024-01-17 15:03 UTC by MedovTimur

2024-01-29 07:34 UTC, LouiseMedova requested changes

2024-01-29 07:34 UTC, LouiseMedova commented on contracts/multi-token/src/lib.rs
> +            from: msg::source(),
`msg::source()` is called several times (also in `burn_impl`)
it's necessary to save `msg::source()` value into variable

2024-01-29 07:34 UTC, LouiseMedova commented on contracts/multi-token/src/lib.rs
> +            to: ZERO_ID,
`ActorId::zero()` instead of `ZERO_ID`

2024-01-29 07:34 UTC, LouiseMedova commented on contracts/multi-token/src/lib.rs
> +            .entry(msg::source())
again calling `msg::source()` several times

2024-01-29 07:34 UTC, LouiseMedova commented on contracts/multi-token/src/lib.rs
> +            .expect("Caller has not approved any accounts")
return `Err` instead of panic

2024-01-29 07:34 UTC, LouiseMedova commented on contracts/multi-token/src/lib.rs
> +        let quantity = self.supply.get_mut(&id).unwrap();
don't use `unwrap()`
you should return `Err` instead

2024-01-29 11:10 UTC, shamilsan approved these changes

2024-01-29 11:10 UTC, shamilsan commented on contracts/concert/src/lib.rs
> +                let mut ids = vec![];
It is better to set capacity if known.
```suggestion
                let mut ids = Vec::with_capacity(actor_md.len());
```

2024-01-29 11:10 UTC, shamilsan commented on contracts/concert/src/lib.rs
> +            .map(|(k, v)| (k, v.into_iter().map(|(k, v)| (k, v)).collect()))
No need use map here
```suggestion
            .map(|(k, v)| (k, v.into_iter().collect()))
```

2024-01-29 11:10 UTC, shamilsan commented on contracts/multi-token/tests/utils.rs
> +    }
I'd rewrite a little bit.

```suggestion
    let expected = if let Some(error) = error {
        Err(error)
    } else {
        Ok(MtkEvent::RevokeApproval {
            from: from.into(),
            to: to.into(),
        })
    };
    assert!(res.contains(&(from, expected.encode())));
```

2024-02-02 08:00 UTC, LouiseMedova approved these changes

2024-02-02 11:04 UTC, merged